# Generated by Django 6.0.6 on 2026-06-28 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_department_hod_department_status_semester_end_date_and_more'),
        ('staff', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('FACULTY', 'Faculty Feedback'), ('SUBJECT', 'Subject Feedback'), ('COURSE', 'Course Feedback'), ('INFRASTRUCTURE', 'Infrastructure Feedback')], default='FACULTY', max_length=20)),
                ('rating', models.IntegerField(default=5)),
                ('comments', models.TextField()),
                ('is_anonymous', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='staff.staff')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='students.student')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='academics.subject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
