# Generated by Django 6.0.6 on 2026-06-28 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('provider', models.CharField(choices=[('MOCK', 'Mock / Rule-Based Local Fallback (Default)'), ('GEMINI', 'Google Gemini AI Api'), ('OPENAI', 'OpenAI ChatGPT Api')], default='MOCK', max_length=20)),
                ('api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('model_name', models.CharField(default='gemini-1.5-flash', max_length=100)),
                ('temperature', models.DecimalField(decimal_places=2, default=0.7, max_digits=3)),
            ],
            options={
                'verbose_name': 'AI Configuration',
                'verbose_name_plural': 'AI Configurations',
            },
        ),
        migrations.CreateModel(
            name='AIAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('intent', models.CharField(default='unknown', max_length=100)),
                ('execution_time_ms', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FALLBACK', 'Fallback'), ('ERROR', 'Error')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AIChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=15)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_chats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
