# Generated by Django 6.0.6 on 2026-06-28 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0003_department_hod_department_status_semester_end_date_and_more'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_letter', models.CharField(max_length=5, unique=True)),
                ('min_score', models.IntegerField()),
                ('max_score', models.IntegerField()),
                ('grade_point', models.IntegerField()),
                ('is_pass', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-grade_point'],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('exam_type', models.CharField(choices=[('INTERNAL', 'Internal Assessment'), ('MIDSEM', 'Mid Semester'), ('MODEL', 'Model Exam'), ('PRACTICAL', 'Practical Exam'), ('VIVA', 'Viva'), ('ENDSEM', 'End Semester')], default='MIDSEM', max_length=15)),
                ('exam_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('maximum_marks', models.IntegerField(default=100)),
                ('passing_marks', models.IntegerField(default=50)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived'), ('RESULTS_PUBLISHED', 'Results Published')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='academics.academicyear')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='academics.course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='academics.department')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='academics.section')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='academics.semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='academics.subject')),
            ],
            options={
                'ordering': ['-exam_date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='StudentMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grade_letter', models.CharField(blank=True, max_length=5)),
                ('grade_point', models.IntegerField(blank=True, default=0)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='marks.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='students.student')),
            ],
            options={
                'ordering': ['student__register_number'],
                'unique_together': {('exam', 'student')},
            },
        ),
    ]
