# Generated by Django 6.0.6 on 2026-06-28 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_academicyear_class_facultysubjectassignment_section_and_more'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='hod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='department',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=15),
        ),
        migrations.AddField(
            model_name='semester',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='semester',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='semester',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=15),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='semester',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='semesters', to='academics.academicyear'),
        ),
        migrations.AddField(
            model_name='class',
            name='class_advisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='class',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='academics.course'),
        ),
        migrations.AddField(
            model_name='class',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='academics.department'),
        ),
        migrations.AddField(
            model_name='class',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='academics.semester'),
        ),
        migrations.AddField(
            model_name='facultysubjectassignment',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='academics.academicyear'),
        ),
        migrations.AddField(
            model_name='facultysubjectassignment',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='academics.department'),
        ),
        migrations.AddField(
            model_name='facultysubjectassignment',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='facultysubjectassignment',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='academics.semester'),
        ),
        migrations.AddField(
            model_name='section',
            name='class_advisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advised_sections', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='section',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='academics.department'),
        ),
        migrations.AddField(
            model_name='section',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='academics.semester'),
        ),
        migrations.AddField(
            model_name='class',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='academics.section'),
        ),
        migrations.AddField(
            model_name='subject',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='academics.department'),
        ),
        migrations.AddField(
            model_name='subject',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='subject',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='academics.semester'),
        ),
        migrations.AddField(
            model_name='facultysubjectassignment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='academics.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('semester', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('semester', 'section')},
        ),
        migrations.AlterUniqueTogether(
            name='facultysubjectassignment',
            unique_together={('faculty', 'subject', 'academic_year')},
        ),
    ]
